### ISSUE TITLE
Add-on crashing on startup

### ISSUE THREAD

**Issue by ekkesa** [giuseppecastaldo/ha-addons#10]
Hi,

I have updated to 1.2.4, and also did a rebuild, but the [issue ](https://github.com/giuseppecastaldo/ha-addons/issues/7) of crashing still persists. It current starts up and crashes immediately.

I managed to capture the log - see below.

Thank you!

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[22:55:10] INFO: Installed custom component.
[2023-01-05T22:55:13.919] [INFO] default - Whatsapp Addon started.
undefined:1
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at useFileAuthState (/utils/useFileAuthState.js:34:43)
    at async WhatsappClient.connect (/whatsapp.js:51:38)
Node.js v18.9.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by giuseppecastaldo** [comment]
> Hi,
> 
> I have updated to 1.2.4, and also did a rebuild, but the [issue ](https://github.com/giuseppecastaldo/ha-addons/issues/7) of crashing still persists. It current starts up and crashes immediately.
> 
> I managed to capture the log - see below.
> 
> Thank you!
> 
> ```
> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service legacy-services: starting
> s6-rc: info: service legacy-services successfully started
> [22:55:10] INFO: Installed custom component.
> [2023-01-05T22:55:13.919] [INFO] default - Whatsapp Addon started.
> undefined:1
> SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at useFileAuthState (/utils/useFileAuthState.js:34:43)
>     at async WhatsappClient.connect (/whatsapp.js:51:38)
> Node.js v18.9.1
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped
> ```

Try to uninstall and reinstall addon.

**Comment by ekkesa** [comment]
Thank you - I tried that, but was unsuccessful.

I will restore a snapshot prior to adding the addon, and try again.

Will keep you posted.

Appreciate your quick response and effort with this.

**Comment by giuseppecastaldo** [comment]
> Thank you - I tried that, but was unsuccessful.
> 
> I will restore a snapshot prior to adding the addon, and try again.
> 
> Will keep you posted.
> 
> Appreciate your quick response and effort with this.

Are you sure that nothing is in cache? Try to manually download add-on from my repository, upload and install.

**Comment by ekkesa** [comment]
After the restore to a backup before the first installation - I reinstalled 1.2.4 and it seems to be stable now.

Thank you for all your effort with this - It is much appreciated!
