### ISSUE TITLE
Componenti stopped

### ISSUE THREAD

**Issue by shevaxsempre** [giuseppecastaldo/ha-addons#11]
[2023-01-07T13:56:56.809] [INFO] default - Whatsapp Addon started.
undefined:10168
} true,
  ^
SyntaxError: Unexpected token t in JSON at position 349788
    at JSON.parse (<anonymous>)
    at useFileAuthState (/utils/useFileAuthState.js:34:43)
    at async WhatsappClient.connect (/whatsapp.js:51:38)
Node.js v18.9.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by giuseppecastaldo** [comment]
> 
> 
> [2023-01-07T13:56:56.809] [INFO] default - Whatsapp Addon started.
> 
> undefined:10168
> 
> } true,
> 
>   ^
> 
> SyntaxError: Unexpected token t in JSON at position 349788
> 
>     at JSON.parse (<anonymous>)
> 
>     at useFileAuthState (/utils/useFileAuthState.js:34:43)
> 
>     at async WhatsappClient.connect (/whatsapp.js:51:38)
> 
> Node.js v18.9.1
> 
> s6-rc: info: service legacy-services: stopping
> 
> s6-rc: info: service legacy-services successfully stopped
> 
> s6-rc: info: service legacy-cont-init: stopping
> 
> s6-rc: info: service legacy-cont-init successfully stopped
> 
> s6-rc: info: service fix-attrs: stopping
> 
> s6-rc: info: service fix-attrs successfully stopped
> 
> s6-rc: info: service s6rc-oneshot-runner: stopping
> 
> s6-rc: info: service s6rc-oneshot-runner successfully stopped

I'm checking the problem, thanks for reporting

**Comment by giuseppecastaldo** [comment]
> [2023-01-07T13:56:56.809] [INFO] default - Whatsapp Addon started.
> undefined:10168
> } true,
> ^
> SyntaxError: Unexpected token t in JSON at position 349788
> at JSON.parse ()
> at useFileAuthState (/utils/useFileAuthState.js:34:43)
> at async WhatsappClient.connect (/whatsapp.js:51:38)
> Node.js v18.9.1
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped

I installed the add-on on a clean instance of Home Assistant and there doesn't seem to be any issues. Maybe it's a cache problem. Try uninstalling the addon completely or doing a rebuild.
