### ISSUE TITLE
Feature Request: Create Polls

### ISSUE THREAD

**Issue by FaserF** [giuseppecastaldo/ha-addons#13]
Hi, thank you for your addon.
Is it possible to add support for polls, as the whatsapp messanger itself supports it? This would be pretty nice and useful for some automations in groups.

**Comment by giuseppecastaldo** [comment]
Sure. I'm working on it.

**Comment by FaserF** [comment]
Wow, that was fast! Thank you so much! 
Docs will be updated once your changes are uploaded, I guess :)

**Comment by FaserF** [comment]
Any hint on how to send a poll? Can’t find the option yet.
Thanks

**Comment by FaserF** [comment]
Any updates on this @giuseppecastaldo ?
