### ISSUE TITLE
sending message to group

### ISSUE THREAD

**Issue by Spartacus68** [giuseppecastaldo/ha-addons#14]
Hi,
the mechanism to send messages to groups is not working, due to the fact, that there is no possibiliy to extract the group-id in the formt  49123456789-1426340220@g.us. All new group ids are in the format: https://chat.whatsapp.com/KOo4uNwF6FT7I4a10XsOj9, where the code after .com / is the new group id and this is currently not working with this version. If there is a workaround, please let me know, or put this into the documetation.

**Comment by giuseppecastaldo** [comment]
> Hi,
> the mechanism to send messages to groups is not working, due to the fact, that there is no possibiliy to extract the group-id in the formt [49123456789-1426340220@g.us](mailto:49123456789-1426340220@g.us). All new group ids are in the format: https://chat.whatsapp.com/KOo4uNwF6FT7I4a10XsOj9, where the code after .com / is the new group id and this is currently not working with this version. If there is a workaround, please let me know, or put this into the documetation.

The group-id can be found only in the received events.

**Comment by Spartacus68** [comment]
Hi,

thank you very much for your reply and sorry to bother you again. But do 
you have a clue how  it can be extracted from the message/event? I found 
nothing about it! There are different cli-tools available (yowsup-cli) 
but curretly nothing is working.

I would be vry helpful if you can give some hints!
Regards,
Spartacus


------ Originalnachricht ------
Von "giuseppecastaldo" ***@***.***>
An "giuseppecastaldo/ha-addons" ***@***.***>
Cc "Spartacus68" ***@***.***>; "Author" 
***@***.***>
Datum 24.01.2023 19:23:42
Betreff Re: [giuseppecastaldo/ha-addons] sending message to group (Issue 
#14)

**Comment by giuseppecastaldo** [comment]
> Hi, thank you very much for your reply and sorry to bother you again. But do you have a clue how it can be extracted from the message/event? I found nothing about it! There are different cli-tools available (yowsup-cli) but curretly nothing is working. I would be vry helpful if you can give some hints! Regards, Spartacus
> […](#)

In the developer tools of Home Assistant listen to event 'new_whatsapp_message' and view key.remoteJid section.

**Comment by Spartacus68** [comment]
Hi,

thanks for your great support, theroetically it work :-)

But for your information:
The message, sent by your addon is not delivered to the destination 
group. Instead of the sent message there is a message from whatsapp :

analogous translation from german:
" Please wait for the message and make sure that the sender is using the 
latest version of whatsapp"

It seems to be that whatsapp recognizes that the message is sent by a 
foreign app. Strangely enough everything works, when addressing a single 
phonenumber!

I am very happy about the addon and i appreciate your work! If you 
consider working out a solution for this issue, I will be very happy to 
support you. Please let me now, how I can help!

Regards,
Spartacus.




------ Originalnachricht ------
Von "giuseppecastaldo" ***@***.***>
An "giuseppecastaldo/ha-addons" ***@***.***>
Cc "Spartacus68" ***@***.***>; "Author" 
***@***.***>
Datum 24.01.2023 20:29:50
Betreff Re: [giuseppecastaldo/ha-addons] sending message to group (Issue 
#14)

**Comment by PSXDupe** [comment]
Is it possible you could explain step by step how to get the group-id.

I have tried to listen to event "new_whatsapp_message", but what do I need to do to trigger a message that will show the group id. I am completely new to this.

**Comment by Hellis81** [comment]
> new_whatsapp_message

Listen to event and it will look like this:

![image](https://github.com/giuseppecastaldo/ha-addons/assets/61010215/ff303d52-4b7f-4cfa-8a60-7c4470fdd0a3)

data.key.remoteJid is the string you need to use in the send message:

![image](https://github.com/giuseppecastaldo/ha-addons/assets/61010215/39f61a13-b60e-4717-826a-dcffdbc32f9e)

**Comment by heula** [comment]
I tried to get the data.key.remoteJid code via the above method but nothing happens when I use new_whatsapp_message for event to subscribe to.

When I press listen, does the required information appear immediately or do I have to be a bit more patient and does it take a bit longer?

Does this information also depend on something?

Sending WhatsApp messages to my mobile number works fine but it does not work to my created group yet.

Thanks.

![2024-09-05 10_13_14-Window](https://github.com/user-attachments/assets/5842d8bc-3206-4153-a42d-209aec995f11)

**Comment by shahonseven** [comment]
> I tried to get the data.key.remoteJid code via the above method but nothing happens when I use new_whatsapp_message for event to subscribe to.

1. you need to add your ha whatsapp number to the group you want to send.
2. while listening to new_whatsapp_message event, try sending a message to the group.
3. your remoteJid key should appear in the event log.

**Comment by heula** [comment]
Maybe I am stupid but nothings happens when I run this automation while listening.
I will not run succesful

clientId: default
  to: https://chat.whatsapp.com/DwXEyEmgy3k2DlgL0d****@g.us # User ID
  body:
    text: Hi it's a simple text message

This one does run succesful but also nothing happens when listening to "new_whatsapp_message"

clientId: default
to: 316********@s.whatsapp.net
body:
  text: Hi it's a simple text message

I still must be doing something wrong.

Thanks.

**Comment by superture** [comment]
> Maybe I am stupid but nothings happens when I run this automation while listening. I will not run succesful
> 
> clientId: default to: https://chat.whatsapp.com/DwXEyEmgy3k2DlgL0d****@g.us # User ID body: text: Hi it's a simple text message
> 
> This one does run succesful but also nothing happens when listening to "new_whatsapp_message"
> 
> clientId: default to: 316********@s.whatsapp.net body: text: Hi it's a simple text message
> 
> I still must be doing something wrong.
> 
> Thanks.

Same here. I can send to single accounts but listening for group id doesn't work.
