### ISSUE TITLE
accented letters and lines

### ISSUE THREAD

**Issue by shevaxsempre** [giuseppecastaldo/ha-addons#15]
hi Giuseppe, sorry for writing to you here. I would need help if you can, I've always had a problem sending messages using the HA service via nodered, basically if in the Message payload filled previously I have a new line ( \n ) the message is not sent. Doing the rreplace and deleting the line is something I never liked, there is a solution what can you advise me? Thank you

**Comment by giuseppecastaldo** [comment]
> hi Giuseppe, sorry for writing to you here. I would need help if you can, I've always had a problem sending messages using the HA service via nodered, basically if in the Message payload filled previously I have a new line ( \n ) the message is not sent. Doing the rreplace and deleting the line is something I never liked, there is a solution what can you advise me? Thank you

I'm sorry, but I've never used nodered

**Comment by jun3280net** [comment]
> hi Giuseppe, sorry for writing to you here. I would need help if you can, I've always had a problem sending messages using the HA service via nodered, basically if in the Message payload filled previously I have a new line ( \n ) the message is not sent. Doing the rreplace and deleting the line is something I never liked, there is a solution what can you advise me? Thank you

Hi @shevaxsempre I'm sure you've figured out a solution by now, but I've posted my learnings here for anyone else interested : 
[https://community.home-assistant.io/t/getting-new-lines-to-display-in-messages-from-call-service-node-for-whatsapp/697765/3](url)
