### ISSUE TITLE
How to send video file?

### ISSUE THREAD

**Issue by chinedu40** [giuseppecastaldo/ha-addons#18]
What is the code necessary to send a video (mp4) file?

**Comment by giuseppecastaldo** [comment]
> What is the code necessary to send a video (mp4) file?

View documentation. It is necessary to specify video file url.

**Comment by giuseppecastaldo** [comment]
> I did this:
> 
> 
> 
> service: whatsapp.send_message
> 
> data:
> 
>   clientId: default
> 
>   to: XXXXXXXXX@s.whatsapp.net
> 
>   body:
> 
>     video:
> 
>       url: snapshots/snapshots_camera.camera.mp4
> 
> 
> 
> Upon receiving the message the play button is there but you are not able to play the video. 

Url must be public, try to move your file in www/ folder and access from https://<your-home-url>/local/<filename>.<file-extrnsion>.

**Comment by chinedu40** [comment]
Same thing happens when i change it to url: http://XXX.XXX.XX.XX:8123/local/tmp/filename.mp4

Then video sends, but when you click play there is no video shown.

**Comment by giuseppecastaldo** [comment]
> Same thing happens when i change it to url: http://XXX.XXX.XX.XX:8123/local/tmp/filename.mp4
> 
> 
> 
> Then video sends, but when you click play there is no video shown. 

Is this url accessible from external network?

**Comment by chinedu40** [comment]
Sorry I think this was my error. 

I was using the home assistant camera record service. I had to uncheck the box that is titled Lookback. After that it works as described.
