### ISSUE TITLE
Listen for messages from specific group or user?

### ISSUE THREAD

**Issue by adamrhoades** [giuseppecastaldo/ha-addons#20]
How would I go about creating an automation that would be triggered by a specific message to a specific group?

I've been able to trigger with a specific message, but anyone could send that message.

Thanks!

**Comment by ekkesa** [comment]
Why not trigger on the new message event and use a template condition to test if it is the correct group?

**Comment by adamrhoades** [comment]
Had a play around with it and realised I could utilise more of the data from the new_whatsapp_message event.

Came up with an automation that checks for a specific message of 'Unlock' and in a specific group using 'remoteJid'

It even announces who has opened the gate by their whatsapp username and sends a reply acknowledging the request.

alias: Whatsapp Unlock Gate
description: ""
trigger:
  - platform: event
    event_type: new_whatsapp_message
condition:
  - condition: template
    value_template: "{{ trigger.event.data.message.conversation == 'Unlock' }}"
  - condition: template
    value_template: "{{ trigger.event.data.key.remoteJid == '********************@g.us' }}"
action:
  - type: turn_on
    device_id: a8066d26bc0d43c2989e967cae*****
    entity_id: switch.gate_beep
    domain: switch
  - data:
      message: Back Gate Unlocked by {{trigger.event.data.pushName}}
      entity_id: media_player.google_assistants
    service: tts.google_say
  - service: whatsapp.send_message
    data:
      clientId: default
      to: ********************@g.us
      body:
        text: Gate Released
  - type: turn_on
    device_id: a8066d26bc0d43c2989e967cae******
    entity_id: switch.gate_release
    domain: switch
mode: single


Thank you for the suggestion!
