### ISSUE TITLE
Send to Group?

### ISSUE THREAD

**Issue by ostgardh** [giuseppecastaldo/ha-addons#24]
I have try to send to Group. But not sure if is working or how to get id nummer?
Test to send Group id I get from invite link.
Is it possibel to send to Group?

**Comment by PSXDupe** [comment]
Same here, cannot get send to group to work at all.

**Comment by giuseppecastaldo** [comment]
> I have try to send to Group. But not sure if is working or how to get id nummer? Test to send Group id I get from invite link. Is it possibel to send to Group?

#14
