### ISSUE TITLE
image, template buttons etc failed

### ISSUE THREAD

**Issue by mupsje** [giuseppecastaldo/ha-addons#26]
Hi again,

Still not able to sent images and all other examples.
please try yourself to install on new Home Assistant 

service: whatsapp.send_message
data:
  clientId: default
  to: 31********@s.whatsapp.net
  body:
    text: Hi it's a template message
    footer: Hello World
  body:
    image:
      url: "https://dummyimage.com/600x400/000/fff.png"
    caption: Simple text

**Comment by goprojojo** [comment]
This works fine for me:

service: whatsapp.send_message
data:
  clientId: default
  to: 316************@s.whatsapp.net
body:
  text: It's a template
  footer: Hello World
  image:
    url: https://dummyimage.com/600x400/000/fff.png
  caption: This is a test
