### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by jbr1989** [giuseppecastaldo/ha-addons#3]
When I install addon show this error:

`Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:124
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 14:55:30 (1 occurrences)
Last logged: 14:55:30

Failed to to call /addons/f4fdf59d_whatsapp_addon/install - The command '/bin/ash -o pipefail -c cd / && npm install -f' returned a non-zero code: 1`

I can't install addon. Only add Repository and click in install addon.

**Comment by giuseppecastaldo** [comment]
> When I install addon show this error:
> 
> `Logger: homeassistant.components.hassio Source: components/hassio/websocket_api.py:124 Integration: Home Assistant Supervisor (documentation, issues) First occurred: 14:55:30 (1 occurrences) Last logged: 14:55:30
> 
> Failed to to call /addons/f4fdf59d_whatsapp_addon/install - The command '/bin/ash -o pipefail -c cd / && npm install -f' returned a non-zero code: 1`
> 
> I can't install addon. Only add Repository and click in install addon.

It seems to be a problem with your home assistant instance. Have you tried with other instances?

**Comment by nasrulll** [comment]
i got this error when starting the addon

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[08:36:47] INFO: Installed custom component.
[2022-11-28T08:36:48.052] [INFO] default - Whatsapp Addon started.
/whatsapp.js:51
        const { state, saveState } = useSingleFileAuthState(this.#path)
                                     ^
TypeError: useSingleFileAuthState is not a function
    at WhatsappClient.connect (/whatsapp.js:51:38)
    at new WhatsappClient (/whatsapp.js:45:14)
    at init (/index.js:97:18)
    at /index.js:111:5
    at Array.forEach (<anonymous>)
    at /index.js:110:19
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
Node.js v18.9.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

--------
Home Assistant 2022.11.4
Supervisor 2022.11.2

**Comment by jbr1989** [comment]
I tried with other instances and it showed same error.

I tried install release 1.2.1 and installed OK. 
Later I tried update to 1.2.2 and it showed same ERROR:
  "The command '/bin/ash -o pipefail -c cd / && npm install -f' returned a non-zero code: 1"

I have Hassio in Raspberry 3 Model B. I don't now if affect.
- Home Assistant Operating System: 9.3
- Home Assistant Core: 2022.11.4
- Home Assistant Supervisor: 2022.11.2

**Comment by giuseppecastaldo** [comment]
> I tried with other instances and it showed same error.
> 
> I tried install release 1.2.1 and installed OK. Later I tried update to 1.2.2 and it showed same ERROR: "The command '/bin/ash -o pipefail -c cd / && npm install -f' returned a non-zero code: 1"
> 
> I have Hassio in Raspberry 3 Model B. I don't now if affect.
> 
> * Home Assistant Operating System: 9.3
> * Home Assistant Core: 2022.11.4
> * Home Assistant Supervisor: 2022.11.2

Have you a more detailed logs?

**Comment by jbr1989** [comment]
I am sorry. I don't have more details
In the HomeAssistant log, nothing else appears.

**Comment by nasrulll** [comment]
its work well now, thank you so much

just confuse how to send to the group

**Comment by giuseppecastaldo** [comment]
> its work well now, thank you so much
> 
> just confuse how to send text to the group

👍

**Comment by jbr1989** [comment]
I tried install addon with docker command and it showed this:

`Step 1/8 : FROM "ghcr.io/home-assistant/armv7-base:3.16"
 ---> 17155f6eba02
Step 2/8 : RUN apk add --no-cache git npm
 ---> Using cache
 ---> 6f939a915873
Step 3/8 : COPY . /
 ---> bb1bfa9bb8a7
Step 4/8 : RUN chmod a+x /run.sh
 ---> Running in b5fd5f71752c
Removing intermediate container b5fd5f71752c
 ---> 2ecd663a9b2c
Step 5/8 : RUN chmod a+x /finish.sh
 ---> Running in 426296d74b6d
Removing intermediate container 426296d74b6d
 ---> ece64c3aa5b0
Step 6/8 : RUN cd / && npm install -f
 ---> Running in c70cf5dc7e1c
using --force Recommended protections disabled.
ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/root/.npm --prefer-offline=fa>
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN skipping integrity check for git dependency ssh://git@github.com/adiwajshing/eslint-config.git
npm ERR! npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchPar>
npm ERR! npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /root/.npm/_cacache/tmp/git-cloneDPnKgH/node_modules/sharp
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compi>
npm ERR! npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-linuxmus>
npm ERR! npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! npm ERR! sharp: Installation error: Prebuilt libvips 8.12.2 binaries are not yet available for linuxmusl-armv7
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /root/.npm/_logs/2022-12-02T16_31_04_537Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-02T16_30_09_169Z-debug-0.log`
