### ISSUE TITLE
Unable to send WhatsApp message

### ISSUE THREAD

**Issue by chinedu40** [giuseppecastaldo/ha-addons#31]
When trying to send WhatsApp messages i get this message despite being connected to WhatsApp web:
[2023-06-09T11:16:58.485] [ERROR] default - Send message failed. Whatsapp disconnected error.

I have tried to remove the containers (standalone), restart home assistant but i am also unable to generate another QR code.

**Comment by adamrhoades** [comment]
Also unable to send messages with the following error:

[2023-06-09T14:10:31.143] [ERROR] default - Send message failed. Whatsapp disconnected error.

Restarting the add-on doesn't help, not being prompted to scan a QR code.

Last known working @ 21:39 BST last night

**Comment by chinedu40** [comment]
I am able to generate a new QR Code but the error is ‘Can’t link new devices as this time, please try again later’

**Comment by chinedu40** [comment]
See https://github.com/giuseppecastaldo/ha-addons/issues/32#issuecomment-1588808096
