### ISSUE TITLE
QR code not successfully scanned on mobile device

### ISSUE THREAD

**Issue by DerRoedie73** [giuseppecastaldo/ha-addons#35]
When I scan the generated QR code with my mobile device, Whatsapp informs me that it is not possible to add new devices. However I am able to successfully add my browser/laptop. Most likely there is something wrong with the generated QR code.

Is this a known issue and can this be fixed so Whatsapp is useable again from HASS?

**Comment by pabloarrieta2022** [comment]
Hello, I don't know if it is correct, but it worked for me!!! I made a fork in which I changed the Bailys version and other values ​​that referred to this repository, uninstalled everything and reinstalled from my fork, it worked correctly although it only sends plain text and photos from cameras without problems.

**Comment by Gavergracht** [comment]
what is the solution for this ? How can I connect with whatsapp without mobile ?

**Comment by DerRoedie73** [comment]
I remove the add-on from this repo and added Pablo Arrieta's repo as a repository for HACS and then installed WhatsApp integration from there. Then I was able to scan the QR code to configure WhatsApp integration

**Comment by Gavergracht** [comment]
> Pablo Arrieta's repo

where can I find this ?

**Comment by DerRoedie73** [comment]
If you are on HASS Supervised then go to the add-on section, add the repository https://github.com/pabloarrieta2022/ha-addons and restart Home Assistant to pick up the change. Then WhatsApp should be available for install

**Comment by Gavergracht** [comment]
thanks mate

**Comment by DerRoedie73** [comment]
This repo does not provide a working QR code to link your WhatsApp. Using the repository from Pablo Arrieta does produce a working QR code so use that one instead.
