### ISSUE TITLE
node-red notification howto?

### ISSUE THREAD

**Issue by youmax01** [giuseppecastaldo/ha-addons#39]
Hi, i have notification working ok with atuomation option, but with node-red notification i can't make it work
Can someone tell me how to write the sentence?, i this working?

{"clientId":"default","to":"391234567890@s.whatsapp.net","body","text":"test"}
![image](https://github.com/giuseppecastaldo/ha-addons/assets/35151341/93962baf-b961-4943-900a-5d7bacd7ae32)

![image](https://github.com/giuseppecastaldo/ha-addons/assets/35151341/3750db0a-bca7-4d25-9592-885c87151f9b)

**Comment by gerard33** [comment]
Not tested but I think the data should be like this.
```
{
   "clientId": "default",
   "to": "391234567890@s.whatsapp.net",
   "body": {
      "text": "test"
   }
}
```

**Comment by youmax01** [comment]
> Not tested but I think the data should be like this.
> 
> ```
> {
>    "clientId": "default",
>    "to": "391234567890@s.whatsapp.net",
>    "body": {
>       "text": "test"
>    }
> }
> ```

thanks Gerard, i  will try!
