### ISSUE TITLE
templating in message

### ISSUE THREAD

**Issue by nicoolaro** [giuseppecastaldo/ha-addons#43]
Does templating work in text message, i am trying to send a temperature sensor value to message but am not receiving it.

plane text works ok

example:

> service: whatsapp.send_message

> data:

>   clientId: default

>   to: 3********@s.whatsapp.net

>   body:

>     text: "{{ states.sensor.livingroom_temperature_temperature.state }}"

**Comment by PiperNigrum** [comment]
You can use a own Script to call the send message 

service: script.whatsapp_send_message
data: 
  message: "{{ states('sensor.your_sensor') }}"


Within your script use text: "{{ message }}"

**Comment by nicoolaro** [comment]
> You can use a own Script to call the send message
> 
> service: script.whatsapp_send_message data: message: "{{ states('sensor.your_sensor') }}"
> 
> Within your script use text: "{{ message }}"

i don't get it, i should creat a script? becasue when i try the code you sent it doesn't work

**Comment by PiperNigrum** [comment]
> > You can use a own Script to call the send message
> 
> > 
> 
> > service: script.whatsapp_send_message data: message: "{{ states('sensor.your_sensor') }}"
> 
> > 
> 
> > Within your script use text: "{{ message }}"
> 
> 
> 
> i don't get it, i should creat a script? becasue when i try the code you sent it doesn't work

Yes - create a new script which calls the WhatsApp send message.

![image](https://github.com/giuseppecastaldo/ha-addons/assets/16720769/e616e385-61e3-4bac-bcc4-88fa7cad0642)

Now you can call your script to pass any message.

![image](https://github.com/giuseppecastaldo/ha-addons/assets/16720769/26c95dfb-25a7-4bda-872e-fa275706ebb4)

Hope it is easier to understand :)

**Comment by nicoolaro** [comment]
> > > You can use a own Script to call the send message
> > 
> > 
> > > 
> > 
> > 
> > > service: script.whatsapp_send_message data: message: "{{ states('sensor.your_sensor') }}"
> > 
> > 
> > > 
> > 
> > 
> > > Within your script use text: "{{ message }}"
> > 
> > 
> > i don't get it, i should creat a script? becasue when i try the code you sent it doesn't work
> 
> Yes - create a new script which calls the WhatsApp send message.
> 
> ![image](https://user-images.githubusercontent.com/16720769/270723384-e616e385-61e3-4bac-bcc4-88fa7cad0642.jpeg)
> 
> Now you can call your script to pass any message.
> 
> ![image](https://user-images.githubusercontent.com/16720769/270723945-26c95dfb-25a7-4bda-872e-fa275706ebb4.jpeg)
> 
> Hope it is easier to understand :)

Thank you for the help much appreaciate it. But message is not sent.
I followed to the letter


![image](https://github.com/giuseppecastaldo/ha-addons/assets/51228711/6ac4fc49-0b90-44cb-acfa-81d7969e4510)

![image](https://github.com/giuseppecastaldo/ha-addons/assets/51228711/35155e1d-6fc4-47a8-a07f-535d57f3e490)

Script is executing but i am not receiving a message

**Comment by PiperNigrum** [comment]
> > > > You can use a own Script to call the send message
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > service: script.whatsapp_send_message data: message: "{{ states('sensor.your_sensor') }}"
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Within your script use text: "{{ message }}"
> 
> > > 
> 
> > > 
> 
> > > i don't get it, i should creat a script? becasue when i try the code you sent it doesn't work
> 
> > 
> 
> > Yes - create a new script which calls the WhatsApp send message.
> 
> > 
> 
> > 
> 
> > Now you can call your script to pass any message.
> 
> > 
> 
> > 
> 
> > Hope it is easier to understand :)
> 
> 
> 
> Thank you for the help much appreaciate it. But message is not sent.
> 
> I followed to the letter
> 
> 
> 
> 
> 
> ![image](https://github.com/giuseppecastaldo/ha-addons/assets/51228711/6ac4fc49-0b90-44cb-acfa-81d7969e4510)
> 
> 
> 
> ![image](https://github.com/giuseppecastaldo/ha-addons/assets/51228711/35155e1d-6fc4-47a8-a07f-535d57f3e490)
> 
> 
> 
> Script is executing but i am not receiving a message

Well try to Check your script with a fix text - e.g. "Test"?
Does it work?

Maybe your sensor is invalid or is null?


I've tried my script and passed no Text (" ").
I did not get a message as well...

**Comment by nicoolaro** [comment]
> > > > > You can use a own Script to call the send message
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > service: script.whatsapp_send_message data: message: "{{ states('sensor.your_sensor') }}"
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Within your script use text: "{{ message }}"
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > i don't get it, i should creat a script? becasue when i try the code you sent it doesn't work
> > 
> > 
> > > 
> > 
> > 
> > > Yes - create a new script which calls the WhatsApp send message.
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > Now you can call your script to pass any message.
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > Hope it is easier to understand :)
> > 
> > 
> > Thank you for the help much appreaciate it. But message is not sent.
> > I followed to the letter
> > ![image](https://user-images.githubusercontent.com/51228711/270730104-6ac4fc49-0b90-44cb-acfa-81d7969e4510.png)
> > ![image](https://user-images.githubusercontent.com/51228711/270730349-35155e1d-6fc4-47a8-a07f-535d57f3e490.png)
> > Script is executing but i am not receiving a message
> 
> Well try to Check your script with a fix text - e.g. "Test"? Does it work?
> 
> Maybe your sensor is invalid or is null?
> 
> I've tried my script and passed no Text (" "). I did not get a message as well...

Nope, fixed works, template don't. I tried with Telegram and all is ok , Whataspp doesn't work. 
Oh well i'll continue debugging, thanks for your help!

**Comment by chonnymon** [comment]
> > > > > > You can use a own Script to call the send message
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > service: script.whatsapp_send_message data: message: "{{ states('sensor.your_sensor') }}"
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > Within your script use text: "{{ message }}"
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > i don't get it, i should creat a script? becasue when i try the code you sent it doesn't work
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Yes - create a new script which calls the WhatsApp send message.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Now you can call your script to pass any message.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Hope it is easier to understand :)
> > > 
> > > 
> > > Thank you for the help much appreaciate it. But message is not sent.
> > > I followed to the letter
> > > ![image](https://user-images.githubusercontent.com/51228711/270730104-6ac4fc49-0b90-44cb-acfa-81d7969e4510.png)
> > > ![image](https://user-images.githubusercontent.com/51228711/270730349-35155e1d-6fc4-47a8-a07f-535d57f3e490.png)
> > > Script is executing but i am not receiving a message
> > 
> > 
> > Well try to Check your script with a fix text - e.g. "Test"? Does it work?
> > Maybe your sensor is invalid or is null?
> > I've tried my script and passed no Text (" "). I did not get a message as well...
> 
> Nope, fixed works, template don't. I tried with Telegram and all is ok , Whataspp doesn't work. Oh well i'll continue debugging, thanks for your help!

Hi, i was looking for an answer to this today.

I have found the following format works, straight in the automation

![Screenshot](https://github.com/giuseppecastaldo/ha-addons/assets/44906583/00bb58cf-7b5a-4723-bf64-2bde640a50f7)

hopefully this is helpful to someone

**Comment by nicoolaro** [comment]
> > > > > > > You can use a own Script to call the send message
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > > service: script.whatsapp_send_message data: message: "{{ states('sensor.your_sensor') }}"
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > > Within your script use text: "{{ message }}"
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > i don't get it, i should creat a script? becasue when i try the code you sent it doesn't work
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > Yes - create a new script which calls the WhatsApp send message.
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > Now you can call your script to pass any message.
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > Hope it is easier to understand :)
> > > > 
> > > > 
> > > > Thank you for the help much appreaciate it. But message is not sent.
> > > > I followed to the letter
> > > > ![image](https://user-images.githubusercontent.com/51228711/270730104-6ac4fc49-0b90-44cb-acfa-81d7969e4510.png)
> > > > ![image](https://user-images.githubusercontent.com/51228711/270730349-35155e1d-6fc4-47a8-a07f-535d57f3e490.png)
> > > > Script is executing but i am not receiving a message
> > > 
> > > 
> > > Well try to Check your script with a fix text - e.g. "Test"? Does it work?
> > > Maybe your sensor is invalid or is null?
> > > I've tried my script and passed no Text (" "). I did not get a message as well...
> > 
> > 
> > Nope, fixed works, template don't. I tried with Telegram and all is ok , Whataspp doesn't work. Oh well i'll continue debugging, thanks for your help!
> 
> Hi, i was looking for an answer to this today.
> 
> I have found the following format works, straight in the automation
> 
> ![Screenshot](https://user-images.githubusercontent.com/44906583/270923841-00bb58cf-7b5a-4723-bf64-2bde640a50f7.png)
> 
> hopefully this is helpful to someone

This worked, thank you!!

**Comment by kalhimeo** [comment]
This add-on is really amazing, but I am facing the same problem when sending a message containing only numbers (which was probably the same bug that nicoolaro was initially facing with his temperature template.

Using the Service developer tool, this does not work : 

```
service: whatsapp.send_message
data:
  clientId: default
  to: xxxxxx@s.whatsapp.net
  body:
    text: 1
```

This does work : 

```
service: whatsapp.send_message
data:
  clientId: default
  to: xxxxxx@s.whatsapp.net
  body:
    text: >-
      1
```

But a template like this which results in a number output does not work : 

```
service: whatsapp.send_message
data:
  clientId: default
  to: xxxxxx@s.whatsapp.net
  body:
    text: >-
      {{ states('sensor.temperature') }}
```

Inserting some non-numeric characters is a temporary fix : 

```
service: whatsapp.send_message
data:
  clientId: default
  to: xxxxxx@s.whatsapp.net
  body:
    text: >-
      {{ states('sensor.temperature') }} .
```

Any idea if this can be fixed on add-on side ?

Thank you very much !

Best regards

**Comment by Squal165** [comment]
Try starting your message with text then template value.

```
service: whatsapp.send_message
data:
  clientId: default
  to: xxxxxx@s.whatsapp.net
  body:
    text: >-
      Temperature value is {{ states('sensor.temperature') }}.
```

**Comment by kalhimeo** [comment]
yes that works for sure, as in my temporary fix above where i simply added a "space and a point" at the end. But it would be better if the bug can be fixed :-) Also in my exemple I used a temperature template to make it easy, but in reality I use this add-on in a chatbot answering queries from a WhatsApp conversation, so I cannot use additional fixed text in the template as it can be anything from a number to a long sentence.

**Comment by kalhimeo** [comment]
I don't know if it s due to the last code reversal from 1.3.4 to 1.3.5, but this bug is unfortunately still present in latest release 1.3.5. 
Log error when the message is only a number : [2024-01-21T00:20:36.028] [ERROR] default - Cannot read properties of undefined (reading 'payload')

**Comment by giuseppecastaldo** [comment]
unfortunately I didn't carefully check the latest pull request. the bug is scheduled for fix
