### ISSUE TITLE
send massage with a picture

### ISSUE THREAD

**Issue by moshik132** [giuseppecastaldo/ha-addons#44]
I want to send a message with a picture.
Does the image have to be on a website?
I saw according to the example that a link to the url is needed.
Is it possible to send an image located in a network folder?

**Comment by julienelasri** [comment]
I'm looking for the same thing
Not successfuly on local netwrok :/

**Comment by pesmi30** [comment]
I can send an image that is on the Internet (url: "https://www.etcetera
I can send an image from my local network (url: "http://192.168.1.134/VRAX/{PHOTO.JPG

But how can I send an image that is on the raspberry where my HomeAssistant is running?

**Comment by PiperNigrum** [comment]
1. image has to be accessable via the internet 
2. use the www folder (https://YOUR_PUBLIC_IP/local/image.jpeg)
