### ISSUE TITLE
Feature request : Send message with Video 

### ISSUE THREAD

**Issue by daknightuk** [giuseppecastaldo/ha-addons#46]
Hello would it be possible to send a message with a video ? 

I have blink camera system and I would like to write an automaton to send me the latest video through whatsapp 
The format of the video I believe is .mp4

**Comment by En3myNightmare** [comment]
It's already possible.

`service: whatsapp.send_message
data:
  clientId: XXX
  to: XXX
  body:
    video:
      url: http://homeassistant:8123/local/videos/video.mp4
`

**Comment by En3myNightmare** [comment]
#18 
It's already possible
