### ISSUE TITLE
Not receive any notification

### ISSUE THREAD

**Issue by miguellandre** [giuseppecastaldo/ha-addons#47]
Hello, I installed the addon, I can send messages and receive them on my cell phone. but I don't receive notification of the message when it arrives. I receive notifications from all my contacts but when it is sent from my home assistant I do not receive any notification.

**Comment by joaofgf** [comment]
same problem here.

**Comment by fatalyzm** [comment]
Normal behaviour, if you send a Message in a WhatsApp group you‘ve also don‘t get a Notification…

**Comment by miguellandre** [comment]
update and everything seems to be fine. can close. thanks
