### ISSUE TITLE
Strange eror

### ISSUE THREAD

**Issue by mupsje** [giuseppecastaldo/ha-addons#5]
{"level":40,"time":"2022-11-28T14:30:45.108Z","pid":83,"hostname":"f4fdf59d-whatsapp-addon","stack":"Error: mutex start\n    at /node_modules/@giuseppecastaldo/baileys/lib/Utils/make-mutex.js:15:31\n    at Object.mutex (/node_modules/@giuseppecastaldo/baileys/lib/Utils/make-mutex.js:35:15)\n    at handleMessage (/node_modules/@giuseppecastaldo/baileys/lib/Socket/messages-recv.js:438:29)\n    at execTask (/node_modules/@giuseppecastaldo/baileys/lib/Socket/messages-recv.js:549:20)\n    at processNodeWithBuffer (/node_modules/@giuseppecastaldo/baileys/lib/Socket/messages-recv.js:545:26)\n    at WebSocket.<anonymous> (/node_modules/@giuseppecastaldo/baileys/lib/Socket/messages-recv.js:563:9)\n    at WebSocket.emit (node:events:513:28)\n    at /node_modules/@giuseppecastaldo/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/node_modules/@giuseppecastaldo/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/node_modules/@giuseppecastaldo/baileys/lib/Socket/socket.js:198:15)","waitOver":true,"msg":"possible mutex deadlock"}

**Comment by mupsje** [comment]
fixed

**Comment by mupsje** [comment]
fixed

**Comment by ekkesa** [comment]
I find this error too randomly - Is the applied fix to rebuild?
