### ISSUE TITLE
Messages on Community Groups not working

### ISSUE THREAD

**Issue by ekkesa** [giuseppecastaldo/ha-addons#51]
This addon is awesome, and is working great.

Unfortunately I noticed, that on the new Community Groups, the messages just stays in a state saying: “Waiting for this message. This may take a while. [Learn more](https://faq.whatsapp.com/3398056720476987/?locale=en_US&eea=0&refsrc=deprecated&_rdr)”

the [Learn more](https://faq.whatsapp.com/3398056720476987/?locale=en_US&eea=0&refsrc=deprecated&_rdr) link hints that it might be a versioning issue.

Also, found [this](https://github.com/salman0ansari/whatsapp-api-nodejs/issues/155) while searching for possible solutions.

**Comment by giuseppecastaldo** [comment]
unfortunately it is a problem related to the different versions of whatsapp and therefore depends exclusively on it
