### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by nuk3man** [giuseppecastaldo/ha-addons#57]
Hi. I don't have an issue but more of a question. While WhatsApp is end-to-end encrypted does logging in with the app somehow not expose all the conversations? When I link my unit with the QR code it says that the system is Ubuntu. Why is that?

**Comment by giuseppecastaldo** [comment]
> Hi. I don't have an issue but more of a question. While WhatsApp is end-to-end encrypted does logging in with the app somehow not expose all the conversations? When I link my unit with the QR code it says that the system is Ubuntu. Why is that?

Yes, it could, but you can read the code of this repository, your conversations only safe
