### ISSUE TITLE
Cannot read properties of undefined (reading 'payload')

### ISSUE THREAD

**Issue by pbn42** [giuseppecastaldo/ha-addons#58]
Hi,
Since the last version (1.3.4) everytime i try to send a message, i get this error in the logs :

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[15:51:28] INFO: Installed custom component.
[2024-01-20T15:51:29.584] [INFO] default - Whatsapp Addon started.
[2024-01-20T15:51:30.139] [INFO] default - default client is ready.
[2024-01-20T15:53:15.572] [ERROR] default - Cannot read properties of undefined (reading 'payload')`

(trying to send the message from the services tab in gome assistant :)

> service: whatsapp.send_message
data:
  clientId: default
  to: 33612345678@s.whatsapp.net
  body:
    text: test

Do you have an idea to fix it please ?

Thanks in advance.

Best regards,

Pierre

**Comment by kalhimeo** [comment]
For info i have exactly the same error here since today's update

**Comment by D3nh0** [comment]
Same issue as well

**Comment by giuseppecastaldo** [comment]
Solved. 
https://github.com/giuseppecastaldo/ha-addons/pull/59

**Comment by pbn42** [comment]
Thanks a lot for your reactivity 🙏

**Comment by D3nh0** [comment]
Thank you for the fix! (And the great add-on, first time using it today)
