### ISSUE TITLE
Error install in armv7

### ISSUE THREAD

**Issue by jbr1989** [giuseppecastaldo/ha-addons#6]
I tried install addon with docker command and it showed this:

Step 1/8 : FROM "ghcr.io/home-assistant/armv7-base:3.16"
 ---> 17155f6eba02
Step 2/8 : RUN apk add --no-cache git npm
 ---> Using cache
 ---> 6f939a915873
Step 3/8 : COPY . /
 ---> bb1bfa9bb8a7
Step 4/8 : RUN chmod a+x /run.sh
 ---> Running in b5fd5f71752c
Removing intermediate container b5fd5f71752c
 ---> 2ecd663a9b2c
Step 5/8 : RUN chmod a+x /finish.sh
 ---> Running in 426296d74b6d
Removing intermediate container 426296d74b6d
 ---> ece64c3aa5b0
Step 6/8 : RUN cd / && npm install -f
 ---> Running in c70cf5dc7e1c
using --force Recommended protections disabled.
ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/root/.npm --prefer-offline=fa>
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN skipping integrity check for git dependency ssh://git@github.com/adiwajshing/eslint-config.git
npm ERR! npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchPar>
npm ERR! npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /root/.npm/_cacache/tmp/git-cloneDPnKgH/node_modules/sharp
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compi>
npm ERR! npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-linuxmus>
npm ERR! npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! npm ERR! sharp: Installation error: Prebuilt libvips 8.12.2 binaries are not yet available for linuxmusl-armv7
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /root/.npm/_logs/2022-12-02T16_31_04_537Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-02T16_30_09_169Z-debug-0.log

_Originally posted by @jbr1989 in https://github.com/giuseppecastaldo/ha-addons/issues/3#issuecomment-1335525659_

**Comment by giuseppecastaldo** [comment]
What does means "I tried install addon with docker command and it showed this", don't you have home assistant supervised?

**Comment by giuseppecastaldo** [comment]
> ```
>     I tried install addon with docker command and it showed this:
> ```
> 
> Step 1/8 : FROM "ghcr.io/home-assistant/armv7-base:3.16" ---> 17155f6eba02 Step 2/8 : RUN apk add --no-cache git npm ---> Using cache ---> 6f939a915873 Step 3/8 : COPY . / ---> bb1bfa9bb8a7 Step 4/8 : RUN chmod a+x /run.sh ---> Running in b5fd5f71752c Removing intermediate container b5fd5f71752c ---> 2ecd663a9b2c Step 5/8 : RUN chmod a+x /finish.sh ---> Running in 426296d74b6d Removing intermediate container 426296d74b6d ---> ece64c3aa5b0 Step 6/8 : RUN cd / && npm install -f ---> Running in c70cf5dc7e1c using --force Recommended protections disabled. ERR! code 1 npm ERR! git dep preparation failed npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/root/.npm --prefer-offline=fa> npm ERR! npm WARN using --force Recommended protections disabled. npm ERR! npm WARN skipping integrity check for git dependency ssh://[git@github.com](mailto:git@github.com)/adiwajshing/eslint-config.git npm ERR! npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchPar> npm ERR! npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin. npm ERR! npm ERR! code 1 npm ERR! npm ERR! path /root/.npm/_cacache/tmp/git-cloneDPnKgH/node_modules/sharp npm ERR! npm ERR! command failed npm ERR! npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compi> npm ERR! npm ERR! sharp: Downloading [https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-linuxmus>](https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-linuxmus%3E) npm ERR! npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies npm ERR! npm ERR! sharp: Installation error: Prebuilt libvips 8.12.2 binaries are not yet available for linuxmusl-armv7 npm ERR! npm ERR! npm ERR! A complete log of this run can be found in: npm ERR! npm ERR! /root/.npm/_logs/2022-12-02T16_31_04_537Z-debug-0.log
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2022-12-02T16_30_09_169Z-debug-0.log
> 
> _Originally posted by @jbr1989 in [#3 (comment)](https://github.com/giuseppecastaldo/ha-addons/issues/3#issuecomment-1335525659)_

What does means "I tried install addon with docker command and it showed this", don't you have home assistant supervised?

**Comment by jbr1989** [comment]
Yes, I have home assistant supervised in one raspberry and It show [https://github.com/giuseppecastaldo/ha-addons/issues/3](url)
I tried in other raspberry with home assitant supervised, but I can install docker containers with terminal and I show previous error.
I supose the error is "libvips 8.12.2" dependence who is incompatible with armv7 of raspberry.

**Comment by giuseppecastaldo** [comment]
> Yes, I have home assistant supervised in one raspberry and It show [https://github.com/giuseppecastaldo/ha-addons/issues/3](url)
> I tried in other raspberry with home assitant supervised, but I can install docker containers with terminal and I show previous error.
> I supose the error is "libvips 8.12.2" dependence who is incompatible with armv7 of raspberry.

I tested the add-on on RPi 3 (Raspbian) & RPi 4 (Ubuntu) without problem. Try to downgrade NodeJS version by adding this in Dockerfile:

 ```Dockerfile
RUN npm install -g n && n 16.15.0
```

before this line:
```Dockerfile
RUN cd / && npm install -f
```
