### ISSUE TITLE
notify service

### ISSUE THREAD

**Issue by rba** [giuseppecastaldo/ha-addons#60]
Would it be possible to implement it as well as notify.* service?

I like to add it into notify groups https://www.home-assistant.io/integrations/group/#notify-groups
and in Alerts https://www.home-assistant.io/integrations/alert/.

**Comment by giuseppecastaldo** [comment]
the solution is to create a script that includes everything, visit the home assistant documentation

**Comment by rba** [comment]
Hi @giuseppecastaldo 
I little more hints where to look would be helpful. May you give me some more details where to start looking?
Cheers,
Roman

**Comment by rba** [comment]
Ok, I have a solution for myself.

I used pyscrpt from HACS.

notify_whatsapp.py:
```
@service("notify.whatsapp_send_message")
def whatsapp_send_message(clientId=None, to=None, body=None):
    whatsapp.send_message(**locals())
````
