### ISSUE TITLE
Add On Installation Error

### ISSUE THREAD

**Issue by stoehron** [giuseppecastaldo/ha-addons#65]
When trying to install the add on I get the following:

"The command '/bin/ash -o pipefail -c cd /Baileys && npm i -f && cd .. && npm install -f' returned a non-zero code: 1"

Looks like a type in the "/bin/ash"   part

My setup on raspberry pi 4 is
Core                          2024.2.1
Supervisor                 2024.01.1
Operating System     11.5
Frontend                   20240207.1

**Comment by gastonc** [comment]
Hello, I have the same problem, did you find any solution?

**Comment by stoehron** [comment]
No unfortunately no solution yet
