### ISSUE TITLE
Images and videos

### ISSUE THREAD

**Issue by willhaggan** [giuseppecastaldo/ha-addons#66]
Hi is it possible to send local images or video clips. I.e from a locally stored security camera clip or snapshot.

**Comment by PiperNigrum** [comment]
See #44

**Comment by willhaggan** [comment]
Thank you for the link, thusis what I got to work from my local home assistant device

service: whatsapp.send_message
data:
  clientId: default
  to: 44##########@s.whatsapp.net
  body:
    image: 
      url: "/config/www/test.jpg"
