### ISSUE TITLE
QRCode does not appear in HA notifications

### ISSUE THREAD

**Issue by cosygarcia** [giuseppecastaldo/ha-addons#67]
I installed this add-on. 
Then I started it but no QR code in HA notifications. Add-on stops by itself.

Here is the log :
````
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[16:27:29] INFO: Installed custom component.
[2024-03-02T16:27:31.154] [INFO] default - Whatsapp Addon started.
[2024-03-02T16:27:31.709] [INFO] default - default require authentication over QRCode, please see your notifications...
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 502".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.9.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
````

My conf :
## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 5.10.0-28-arm64
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1404
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 59.9 GB
disk_used | 46.7 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | SQLite Web (4.1.0), Terminal & SSH (9.8.1), InfluxDB (5.0.0), Mosquitto broker (6.4.0), File editor (5.6.0), Portainer (2.19.4-3), MyElectricalData (0.12.0), Whatsapp (1.3.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 7
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 février 2024 à 00:59
-- | --
current_recorder_run | 29 février 2024 à 19:29
estimated_db_size | 2478.06 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by mcgnai** [comment]
it does the same thing to me too... solutions?

**Comment by JamLaMin** [comment]
Same here

**Comment by seba7667** [comment]
Same on my end too
