### ISSUE TITLE
Send message failed. Whatsapp disconnected error.

### ISSUE THREAD

**Issue by norbertohenriques** [giuseppecastaldo/ha-addons#79]
This add-on was working just fine until a few hours ago, when it started throwing the following error:

[ERROR] default - Send message failed. Whatsapp disconnected error.

**Comment by fmsfmsfms** [comment]
i have the same problem in 3 hours ago the add-on stoped working 
i hope it get fixd soon

**Comment by 5yukri** [comment]
same here, few hours ago it stopped working

**Comment by dressie** [comment]
+1. Tried to reconnect, but not getting a QR-code.

**Comment by moryoav** [comment]
Same here. I really hope this can be fixed, I'm using this addon quite a lot.

**Comment by Garreth2013** [comment]
Same problem here form last night, tried re-install as well. Dont get QR any longer.

**Comment by TheSimTek** [comment]
Same here, tried to reinstall but no QR code to connect device.  Rolled back to a week ago and still no go.

**Comment by filip-heens** [comment]
same here, just posting to follow the thread ;-)

**Comment by moritzmaier84** [comment]
+1

one of my fav. addons. a fix would be so nice!

**Comment by lcsneil** [comment]
Exactly the same for me as well.

**Comment by scorbacella** [comment]
same problem

core-2024.8.2
supervisor-2024.08.0
Home Assistant OS 13.1

**Comment by scorbacella** [comment]
I removed the device from whatsapp and reinstalled the add on but the QRcode doesn't appear.
Please help.
Thanks

**Comment by mattdenboer** [comment]
Same here, I would very much appreciate if you could check what went wrong.

thanks for your help!

**Comment by Garreth2013** [comment]
Looks like it’s from Baileys,  needs to be updated and use the correct version: https://github.com/WhiskeySockets/Baileys/issues/999

**Comment by moritzmaier84** [comment]
> Looks like it’s from Baileys, needs to be updated and use the correct version: [WhiskeySockets/Baileys#999](https://github.com/WhiskeySockets/Baileys/issues/999)

I don't get it. What is Baileys and how did you fix that stuff here? Thx

**Comment by AlexPetrar** [comment]
i downgraded to 1.3.5 and that did the trick

**Comment by scorbacella** [comment]
I'd downgrade too (just to try) but I don't have a backup of June.
Is there an alternative method to go back one release?

**Comment by AlexPetrar** [comment]
you can download the 1.3.5 release from this github and manualy copy it to the addons folder on your ha and from there install it as a local addon

**Comment by scorbacella** [comment]
Downloaded and copied. Do you know where I can find a easy step by step guide to install from local folder?
Thanks

**Comment by scorbacella** [comment]
> you can download the 1.3.5 release from this github and manualy copy it to the addons folder on your ha and from there install it as a local addon

I downgraded to 1.3.5 following your instructions. The QRcode appears and the add on works again.  
Thanks

**Comment by ekkesa** [comment]
How did you get the docker container to build? Did you copy only the custom_components folder contents or the whole structure?

**Comment by lcsneil** [comment]
How do you install from the fork?
Tried adding repository https://github.com/giuseppecastaldo/ha-addons/tree/revert-55-patch-1 
But home assistant errors and says not found.

**Comment by ekkesa** [comment]
Add my repo to HACS and install from there.

**Comment by scorbacella** [comment]
> How did you get the docker container to build? Did you copy only the custom_components folder contents or the whole structure?
> 
> UPDATE: I created a fork with version 1.3.5, until a fix is available, then I will kill off the fork again. Installed from the fork, and it is working 100%. Thx!

Hi,
unzip the archive and copy the addon folder (the folder "whatsapp_addon" containing the config.yaml and other sfuff) the in /addons/local of HA. Than restart HA and you will see the local add on in the top of the other add ons in the add on menu of HA. 
hope this helps

**Comment by moryoav** [comment]
I can confirm that the simplest fix is to uninstall the current addon, add the following repo to the list of addon repos - "https://github.com/ekkesa/ha-addons" then look for Whatsapp and make sure you choose the one that's version 1.35 and not 1.4, and install it. The QR code comes up right away, paired successfully, I then restarted although I'm not sure that was needed and now everything works, I didn't need to change any automations or anything, so it was quite painless.

**Comment by moritzmaier84** [comment]
How can I add AddOn Repos into HACS? I'm getting an error message if I try.

**Comment by moritzmaier84** [comment]
> I can confirm that the simplest fix is to uninstall the current addon, add the following repo to the list of addon repos - "https://github.com/ekkesa/ha-addons" then look for Whatsapp and make sure you choose the one that's version 1.35 and not 1.4, and install it. The QR code comes up right away, paired successfully, I then restarted although I'm not sure that was needed and now everything works, I didn't need to change any automations or anything, so it was quite painless.

If I click on "Install" the "wheel" is turning and turning but nothing happens. And idea what's my mistake?

**Comment by philippe-tc** [comment]
Same here. Ik removed the addon, rebooted HA, installed again, rebooted HA, but can’t send any WA-messages. It has been working heren, but stopped doing what it should do.
No authentication came up after new installation.

The documentation that comes with this addon doesn’t say anything about the ‘
Configuration’ tab. it standard shows only ‘default’ as client. Shouldn’t I add my own number here? In what format? Starting with +, than country number etc (like +31655123456) or shoud it be without the + (like 31655123456) or should it be like the user ID that you use when sending a message (like 31655123456s.whatsapp.net)?
Or is nothing needed here?
Ik hope you can expand the ‘user manual’ (in the Configuration tab) on this point. Even is no extra action here is needed, than please tell us there. And tell us there what this tab is for and when and how to use it.

And how can I re-authenitcate my phone number? Because to me it looks like this is the problem…

**Comment by moritzmaier84** [comment]
> Same here. Ik removed the addon, rebooted HA, installed again, rebooted HA, but can’t send any WA-messages. It has been working heren, but stopped doing what it should do. No authentication came up after new installation.
> 
> The documentation that comes with this addon doesn’t say anything about the ‘ Configuration’ tab. it standard shows only ‘default’ as client. Shouldn’t I add my own number here? In what format? Starting with +, than country number etc (like +31655123456) or shoud it be without the + (like 31655123456) or should it be like the user ID that you use when sending a message (like 31655123456s.whatsapp.net)? Or is nothing needed here? Ik hope you can expand the ‘user manual’ (in the Configuration tab) on this point. Even is no extra action here is needed, than please tell us there. And tell us there what this tab is for and when and how to use it.
> 
> And how can I re-authenitcate my phone number? Because to me it looks like this is the problem…
> 
> I’m using version 1.4.0 on Home Assistant, core 2024.8.2 and OS 13.1

Read the thread, there is an easy fix.

**Comment by filip-heens** [comment]
I switched to callmebot.com.. as I only had one script to change (automations call that script and provide the text :-D) it was not a big thing to change... only downside, it a payable service (1€ per month if you want to send with your own number and 6€ a month if you want to send to multiple numbers)

**Comment by philippe-tc** [comment]
> > Same here. Ik removed the addon, rebooted HA, installed again, rebooted HA, but can’t send any WA-messages. It has been working heren, but stopped doing what it should do. No authentication came up after new installation.
> > The documentation that comes with this addon doesn’t say anything about the ‘ Configuration’ tab. it standard shows only ‘default’ as client. Shouldn’t I add my own number here? In what format? Starting with +, than country number etc (like +31655123456) or shoud it be without the + (like 31655123456) or should it be like the user ID that you use when sending a message (like 31655123456s.whatsapp.net)? Or is nothing needed here? Ik hope you can expand the ‘user manual’ (in the Configuration tab) on this point. Even is no extra action here is needed, than please tell us there. And tell us there what this tab is for and when and how to use it.
> > And how can I re-authenitcate my phone number? Because to me it looks like this is the problem…
> > I’m using version 1.4.0 on Home Assistant, core 2024.8.2 and OS 13.1
> 
> Read the thread, there is an easy fix.

You mean to install version 1.35 (is that 1.3.5?) and not 1.40?
I don’t get any choise to what version to install. Please help how to install version 1.35 (1.3.5?).

**Comment by moritzmaier84** [comment]
> > > Same here. Ik removed the addon, rebooted HA, installed again, rebooted HA, but can’t send any WA-messages. It has been working heren, but stopped doing what it should do. No authentication came up after new installation.
> > > The documentation that comes with this addon doesn’t say anything about the ‘ Configuration’ tab. it standard shows only ‘default’ as client. Shouldn’t I add my own number here? In what format? Starting with +, than country number etc (like [+31655123456](tel:+31655123456)) or shoud it be without the + (like [31655123456](tel:31655123456)) or should it be like the user ID that you use when sending a message (like 31655123456s.whatsapp.net)? Or is nothing needed here? Ik hope you can expand the ‘user manual’ (in the Configuration tab) on this point. Even is no extra action here is needed, than please tell us there. And tell us there what this tab is for and when and how to use it.
> > > And how can I re-authenitcate my phone number? Because to me it looks like this is the problem…
> > > I’m using version 1.4.0 on Home Assistant, core 2024.8.2 and OS 13.1
> > 
> > 
> > Read the thread, there is an easy fix.
> 
> You mean to install version 1.35 (is that 1.3.5?) and not 1.40? I don’t get any choise to what version to install. Please help how to install version 1.35 (1.3.5?).

It‘a all said here, you need to add this source:

„ I can confirm that the simplest fix is to uninstall the current addon, add the following repo to the list of addon repos - "https://github.com/ekkesa/ha-addons" then look for Whatsapp and make sure you choose the one that's version 1.35 and not 1.4, and install it. The QR code comes up right away, paired successfully, I then restarted although I'm not sure that was needed and now everything works, I didn't need to change any automations or anything, so it was quite painless.“

**Comment by philippe-tc** [comment]
Exactly that is what I did. To be more specific:
Uninstalled the addon, reboot HA, go to addon shop > repositories, remove the https://github.com/giuseppecastaldo/ha-addons repository, reboot HA, TRY to add the https://github.com/ekkesa/ha-addons repository, but GET the removed https://github.com/giuseppecastaldo/ha-addons repository again.

So the problem is: HOW can I add this ekkesa repository?

![IMG_4590](https://github.com/user-attachments/assets/261d3fbf-613d-4937-a638-e194552f9c59)
![IMG_4591](https://github.com/user-attachments/assets/8dba4998-b384-4308-b835-29085fcee327)

**Comment by moryoav** [comment]
Yeah, that's fine (it's a fork so Home Assistant is just showing you that name of the original, it's the same for me) now if you'll look for Whatsapp you'll see you're getting version 1.35

**Comment by norbertohenriques** [comment]
Any chance to get this fixed on this add-on? I would like to keep this one installed instead of switching to a temporary fork.

**Comment by philippe-tc** [comment]
> Yeah, that's fine (it's a fork so Home Assistant is just showing you that name of the original, it's the same for me) now if you'll look for Whatsapp you'll see you're getting version 1.35

Hmm, rather frustrating. First that the version is NOT 1.35 but 1.3.5. But most frustrating that nobody tells me in this procedure that when I try to install the ekkesa repository, that it succeeds, even though you see gioseppecastaldo again. For me that was a signal that it did NOT succeed…🤬

**Comment by mauriluk** [comment]
anche a me stesso problema dalla versione 2024.8 
non invia più messaggi whatsapp

**Comment by matteoopc** [comment]
> > > > Same here. Ik removed the addon, rebooted HA, installed again, rebooted HA, but can’t send any WA-messages. It has been working heren, but stopped doing what it should do. No authentication came up after new installation.
> > > > The documentation that comes with this addon doesn’t say anything about the ‘ Configuration’ tab. it standard shows only ‘default’ as client. Shouldn’t I add my own number here? In what format? Starting with +, than country number etc (like +31655123456) or shoud it be without the + (like 31655123456) or should it be like the user ID that you use when sending a message (like 31655123456s.whatsapp.net)? Or is nothing needed here? Ik hope you can expand the ‘user manual’ (in the Configuration tab) on this point. Even is no extra action here is needed, than please tell us there. And tell us there what this tab is for and when and how to use it.
> > > > And how can I re-authenitcate my phone number? Because to me it looks like this is the problem…
> > > > I’m using version 1.4.0 on Home Assistant, core 2024.8.2 and OS 13.1
> > > 
> > > 
> > > Read the thread, there is an easy fix.
> > 
> > 
> > You mean to install version 1.35 (is that 1.3.5?) and not 1.40? I don’t get any choise to what version to install. Please help how to install version 1.35 (1.3.5?).
> 
> It‘a all said here, you need to add this source:
> 
> „ I can confirm that the simplest fix is to uninstall the current addon, add the following repo to the list of addon repos - "https://github.com/ekkesa/ha-addons" then look for Whatsapp and make sure you choose the one that's version 1.35 and not 1.4, and install it. The QR code comes up right away, paired successfully, I then restarted although I'm not sure that was needed and now everything works, I didn't need to change any automations or anything, so it was quite painless.“

Thanks! Works…

**Comment by 5yukri** [comment]
> Hi, If you get problems with the fork repo you can try this way; download the zip from here: https://github.com/giuseppecastaldo/ha-addons/releases/tag/v1.3.5 Unzip and copy the folder "whatsapp_addon" in /addons/local of your HA. (You need to have configured "Samba share" add on in order to access the filesystem. Create /local subfolder if there is not). Then restart HA. When you click the "add-on store" button in the supervisor menu of HA, you see the the Whatsapp 1.3.5 add on under the "local add ons" label. Disinstall the 1.4.0 version and install the 1.3.5. Hope this helps.

can this just be done using file editor?

**Comment by scorbacella** [comment]
I think you need to change some permissions to allow the file editor to see other folders besides /config folder.
The easiest way is to install Samba share add on.

**Comment by andreprandina** [comment]
Same here. After 2024.8, nothing happens. No messages, cant´s send or receive. Neither the QR code to authenticate.

**Comment by jtxwnssm** [comment]
Hier het zelfde probleem! Heb Addon 1.4.0 helemaal verwijderd.HA opnieuw opgestart en onder de Back-Ups de Addon Whatsapp 1.3.5 gezocht daarop dubbel click en aanvinken en Restore. En alles draaid weer met dezefde automatiseringen en kreeg ook weer QR code!
![Schermopname (19)](https://github.com/user-attachments/assets/e3384397-1c64-4f7d-a972-796f08d8f707)
![Schermopname (20)](https://github.com/user-attachments/assets/1a59a46e-acdd-4f53-a9ea-cc220f72cfe5)
![Schermopname (21)](https://github.com/user-attachments/assets/32bc001e-374a-4ee9-b800-bd401e9446c1)
![Schermopname (22)](https://github.com/user-attachments/assets/76d17bfb-90d8-4fc5-9a21-2265280aeb57)
![Schermopname (23)](https://github.com/user-attachments/assets/080d87b6-7779-45c5-ad92-7e2f80538928)

**Comment by kmg454** [comment]
Logfile looks different then before, seems the clients are not loaded into the configuration.

**Comment by Marcin685** [comment]
i have error in nodered: `"HomeAssistantError: HTTPConnectionPool(host='f4fdf59d-whatsapp-addon', port=3000): Max retries exceeded with url: /sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29c6e930>: Failed to establish a new connection: [Errno -5] Name has no usable address'))"`. I'm reinstall to 1.3.5. Maybe this is the end of free api from Meta?

**Comment by lcsneil** [comment]
Still working for me - 1.3.5 installed.

_Core - 2024.8.3
Supervisor - 2024.08.0_

**Comment by kmg454** [comment]
Strange that this add-on version 1.40 is not working anymore already for a couple of days and the developer does not respond with a new version.

**Comment by justinswabey** [comment]
I've had the same issues and, using advice above, was able to downgrade to 1.3.5. I then got the QR codes and was able to login with my phone. But the addon still doesn't work. When I try to send a whatsapp with an automation I get the message "Error running action - Unknown Error" which is not very helpful. My feeling is that something was changed by a HA core update, or by WhatsApp which has rendered this addon useless and unfortunately the developer doesn't seem to be supporting it any more. A great shame as it was a really useful addon.

Does anybody know of any alternatives ? I tried callmebot, but I couldn't get it to work to trigger actions when whatsapp groups received massages, which is what I need.

**Comment by justinswabey** [comment]
> i have error in nodered: `"HomeAssistantError: HTTPConnectionPool(host='f4fdf59d-whatsapp-addon', port=3000): Max retries exceeded with url: /sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29c6e930>: Failed to establish a new connection: [Errno -5] Name has no usable address'))"`. I'm reinstall to 1.3.5. Maybe this is the end of free api from Meta? When i try ping to domain s.whatsapp.net i have timeouts.

Yes, I see the same error in my traces with 1.3.5. Such a shame if this is the end to this addon, which was so useful.

**Comment by philippe-tc** [comment]
Version 1.3.5 works perfectly here.
If you’re having trouble something else must be wrong. Something in your configuration?

Core 2024.8.2
Supervisor 2024.08.0
Operating System 13.1

**Comment by justinswabey** [comment]
> If you’re having trouble,something else must be wrong. Something in your configuration?

Me and a lot of others. And we never changed anything before it stopped working. This must be an issue at the Meta / HA end

**Comment by justinswabey** [comment]
[2024-09-01T09:11:34.057] [INFO] default - Whatsapp Addon started.
[2024-09-01T09:11:34.756] [INFO] default - sim2 require authentication over QRCode, please see your notifications...
[2024-09-01T09:11:35.066] [INFO] default - default client is ready.
[2024-09-01T09:11:55.317] [INFO] default - sim2 client is ready.

Everything looks OK at the addon end. Whatsapp server just notresponding to requests

**Comment by filip-heens** [comment]
> Does anybody know of any alternatives ? I tried callmebot, but I couldn't get it to work to trigger actions when whatsapp groups received massages, which is what I need.

Have you tried the paying version (textmebot) I think you need that one for groups...
Also support isn't really fast, but it is there.
It's working fine here (but I only send, I'm not receiving)

**Comment by benjamin-dcs** [comment]
> Strange that this add-on version 1.40 is not working anymore already for a couple of days and the developer does not respond with a new version.

Strange that people don't seem to understand that (the majority of) the HA addons are developed by people spending their spare time developing it. No structural compensation, just some gifts. Be happy that others found a working workaround by reverting to 1.3.5. If you are so keen on getting 1.4.0+ to work again get into coding and create a pullrequest :) (and buy @giuseppecastaldo a coffee in the meantime)

**Comment by AUSF** [comment]
> > i have error in nodered: `"HomeAssistantError: HTTPConnectionPool(host='f4fdf59d-whatsapp-addon', port=3000): Max retries exceeded with url: /sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29c6e930>: Failed to establish a new connection: [Errno -5] Name has no usable address'))"`. I'm reinstall to 1.3.5. Maybe this is the end of free api from Meta? When i try ping to domain s.whatsapp.net i have timeouts.
> 
> Yes, I see the same error in my traces with 1.3.5. Such a shame if this is the end to this addon, which was so useful. I was using the addon to send me daily whatsapps. Last one I received was 22/08. Some here say that their addon is still working. Maybe meta disabling service incrementally? I'm in UK

Hi, I was getting the same error after 1.3.5 setup as a local addon, but after a full HA machine reboot it has disappeared...

**Comment by justinswabey** [comment]
> Hi, I was getting the same error after 1.3.5 setup as a local addon, but after a full HA machine reboot it has disappeared...

Yes! It worked, thank you. Think I had re-started so many times that I forgot to...

So for me:
- log out from whatsapp
- uninstall 1.4
- install 1.3.5 (instructions in this thread)
- start addon
- log in through QR codes
- re-start HA
- disable auto update as there is clearly an issue with 1.4 for some platforms

From my POV, I absolutely appreciate all of the work that people do for HA and try my best with my meagre knowledge to help iron stuff out. Thanks @giuseppecastaldo for a really useful addon

**Comment by justinswabey** [comment]
Just looking at the Github page for Baileys, installing / updating that is beyond my expertise and probably that of most people here with the same issue. Downgrade to 1.3.5 workaround is the fallback for us...

**Comment by philippe-tc** [comment]
Such a shame that some just say (complain?) that this is 'beyond your expertise'. And then also add that this probably applies to most people here.

You know you are on a platform for techies here? Going there to complain about a lack of technical knowledge comes across as rather strange.

Instead of asking for further help, complaints are made. You won't get ahead that way. Asking further questions with an open mind (how to do something, for example) often gets you a lot further.

**Comment by philippe-tc** [comment]
Such a shame that some just say (complain?) that this is 'beyond their expertise'. And then also add that this is probably true for most people here.

You know you are on a platform for techies here? Going there to complain about a lack of technical knowledge comes across as rather strange.

Instead of asking for further help, complaints are made. You won't get ahead that way. Asking further questions with an open mind (how to do something, for example) often gets you a lot further.

**Comment by philippe-tc** [comment]
> Just looking at the Github page for Baileys, installing / updating that is beyond my expertise and probably that of most people here with the same issue. Downgrade to 1.3.5 workaround is the fallback for us...

Please speak for yourself and not for others. They are perfectly capable of doing that themselves.

**Comment by justinswabey** [comment]
> Such a shame that some just say (complain?) that this is 'beyond their expertise'. And then also add that this is probably true for most people here.

I'm certainly not complaining (sounds like you are though). Just offering advice to those at my humble level as there was at least one user who had no idea what Baileys was and most others who have post are going for the downgrade, which also implies that they are not keen to go down a more complicated route. Speaking personally, I have a go at many, many different things in my life and unfortunately just don't have the time to become an expert in all of them
> 
> You know you are on a platform for techies here? Going there to complain about a lack of technical knowledge comes across as rather strange.

No, I'm not complaining about lack of technical knowledge at all. Just admitting it. I'm looking for helpful technical advice, not unhelpful criticism. You could just explain what I need to do.
> 
> Instead of asking for further help, complaints are made. You won't get ahead that way. Asking further questions with an open mind (how to do something, for example) often gets you a lot further.
Thanks for the life advice, but I'm happy with my current path and have much better things to do than spend it having a go at people for no good reason. My advice to you: Be a little more helpful and constructive and not always so quick to criticise.

**Comment by ekkesa** [comment]
> How did you get the docker container to build? Did you copy only the custom_components folder contents or the whole structure?
> 
> UPDATE: I created a fork with version 1.3.5, until a fix is available, then I will kill off the fork again. Installed from the fork, and it is working 100%. Thx!

Temporary Repo removed.

**Comment by skydado** [comment]
Hi, I do confirm this issue is really annoying.
Tried deleting cookies and HA files, but after an unpredictable time, relogin is required again.

If useful, I share my automation that performs the integration reload when the HA relogin notification appears/is required.
Unfortunately, HA not always detects that a relogin is required, so it happens that the automation is not triggered even when the integration is not working due to the relogin requirement.

```
alias: Alexa-Media-Player reload integration if relogin required
description: Alexa-Media-Player reload integration if relogin required
trigger:
  - platform: event
    event_type: alexa_media_relogin_required
condition: []
action:
  - data:
      entry_id: 01J8D0BSTG8KXRCW57412M992W
    action: homeassistant.reload_config_entry
mode: single
```

The config entry id is found in config/.storage/core.config_entries for the one you want to reload.
