### ISSUE TITLE
No QR code

### ISSUE THREAD

**Issue by yebaws** [giuseppecastaldo/ha-addons#80]
Recently I stopped getting whatsapps through my automations that call this addon. No errors showing in the automation traces, but no whatsapp messages, I tried logging off linked devices from my phone, uninstalling and re-installing the addon and re-starting HA, but no QR codes appear as persistent notifications. When I go to configuration "default" is already there as a client (although it can't be logged on). I can add other clients and re-start, but still no QR codes. Any ideas please, or what logs / info do you need top see?

**Comment by FaserF** [comment]
Most likely same issue as #79
