### ISSUE TITLE
Addon Crashes after send message

### ISSUE THREAD

**Issue by TGMivo** [giuseppecastaldo/ha-addons#9]
It crashes after send message via automation.
Need to restart addon, Watchdog dit not work.

Current version: 1.2.3

Home Assistant 2022.12.8
Supervisor 2022.12.1
Frontend-versie: 20221213.1 - latest

**Comment by ekkesa** [comment]
Unfortunately it seems to be more unstable now on 1.2.3 after the update. It seems to stop and the log is empty, so unfortunately I can't even supply information on why it crashed.

I will scratch around in the docker container to see if I can find some log traces.

**Comment by M4dMike** [comment]
Same for me:

> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service legacy-services: starting
> s6-rc: info: service legacy-services successfully started
> [09:19:57] INFO: Installed custom component.
> [2023-01-03T09:20:00.059] [INFO] default - Whatsapp Addon started.
> [2023-01-03T09:20:01.083] [INFO] default - default client is ready.
> /whatsapp.js:125
>             const msg = messages[0]
>                         ^
> ReferenceError: messages is not defined
>     at EventEmitter.<anonymous> (/whatsapp.js:125:25)
>     at EventEmitter.emit (node:events:513:28)
>     at EventEmitter.<anonymous> (/node_modules/@giuseppecastaldo/baileys/lib/Utils/event-buffer.js:40:16)
>     at EventEmitter.emit (node:events:513:28)
>     at Object.flush (/node_modules/@giuseppecastaldo/baileys/lib/Utils/event-buffer.js:73:16)
>     at processNodeWithBuffer (/node_modules/@giuseppecastaldo/baileys/lib/Socket/messages-recv.js:552:12)
> Node.js v18.9.1
> s6-rc: info: service legacy-services: stopping
> s6-rc: info: service legacy-services successfully stopped
> s6-rc: info: service legacy-cont-init: stopping
> s6-rc: info: service legacy-cont-init successfully stopped
> s6-rc: info: service fix-attrs: stopping
> s6-rc: info: service fix-attrs successfully stopped
> s6-rc: info: service s6rc-oneshot-runner: stopping
> s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by shevaxsempre** [comment]
> Stessa cosa per me:
> 
> ```
> > s6-rc: info: service s6rc-oneshot-runner: starting
> > s6-rc: info: service s6rc-oneshot-runner successfully started
> > s6-rc: info: service fix-attrs: starting
> > s6-rc: info: service fix-attrs successfully started
> > s6-rc: info: service legacy-cont-init: starting
> > s6-rc: info: service legacy-cont-init successfully started
> > s6-rc: info: service legacy-services: starting
> > s6-rc: info: service legacy-services successfully started
> > [09:19:57] INFO: Installed custom component.
> > [2023-01-03T09:20:00.059] [INFO] default - Whatsapp Addon started.
> > [2023-01-03T09:20:01.083] [INFO] default - default client is ready.
> > /whatsapp.js:125
> >             const msg = messages[0]
> >                         ^
> > ReferenceError: messages is not defined
> >     at EventEmitter.<anonymous> (/whatsapp.js:125:25)
> >     at EventEmitter.emit (node:events:513:28)
> >     at EventEmitter.<anonymous> (/node_modules/@giuseppecastaldo/baileys/lib/Utils/event-buffer.js:40:16)
> >     at EventEmitter.emit (node:events:513:28)
> >     at Object.flush (/node_modules/@giuseppecastaldo/baileys/lib/Utils/event-buffer.js:73:16)
> >     at processNodeWithBuffer (/node_modules/@giuseppecastaldo/baileys/lib/Socket/messages-recv.js:552:12)
> > Node.js v18.9.1
> > s6-rc: info: service legacy-services: stopping
> > s6-rc: info: service legacy-services successfully stopped
> > s6-rc: info: service legacy-cont-init: stopping
> > s6-rc: info: service legacy-cont-init successfully stopped
> > s6-rc: info: service fix-attrs: stopping
> > s6-rc: info: service fix-attrs successfully stopped
> > s6-rc: info: service s6rc-oneshot-runner: stopping
> > s6-rc: info: service s6rc-oneshot-runner successfully stopped
> ```

same log for me with 1.2.3!
instead with 1.2.2 the recipient not can receive message with buttons.

**Comment by giuseppecastaldo** [comment]
Try the new release, if there are problems open a new issue
